services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    command: sh -c "pnpm install && pnpm dev"